/**
 * @file codelab.js
 * @description Client-side navigation engine and interactive runtime for Codelabs.
 * 
 * Transforms the static HTML markup generated by `tools/md-to-codelab.js` into an interactive,
 * multi-step tutorial interface with:
 *   - Fixed top title bar with breadcrumbs/menu and real-time remaining duration estimation.
 *   - Collapsible drawer listing all steps with ordered indicators and direct navigation.
 *   - Step state management, URL hash synchronization (`#0`, `#1`, ...), and keyboard/FAB controls.
 *   - Animated step transitions (`step-enter-next`, `step-enter-previous`).
 *   - Session persistence via `localStorage` (`progress_<codelab-id>`).
 *   - Code block syntax highlighting via `window.prettyPrintOne`
 */

(function () {
  'use strict';

  /**
   * Dispatches a custom bubbling event on `document.body` for analytics or parent listeners.
   *
   * @param {Element} root - The target element originating the action.
   * @param {string} name - Event name .
   * @param {Object} [detail={}] - Additional event payload.
   */
  // function dispatch(root, name, detail) {
  //   document.body.dispatchEvent(new CustomEvent(name, {
  //     detail: detail || {},
  //     bubbles: true
  //   }));
  // }

  /**
   * Helper utility to create a DOM element with optional class name and text content.
   *
   * @param {string} tagName - HTML tag name to create (e.g. 'div', 'h2', 'span').
   * @param {string} [className] - Optional class attribute value.
   * @param {string} [text] - Optional textContent.
   * @returns {HTMLElement} The created DOM element.
   */
  function createElement(tagName, className, text) {
    var element = document.createElement(tagName);
    if (className) {
      element.className = className;
    }
    if (text !== undefined) {
      element.textContent = text;
    }
    return element;
  }

  /**
   * Helper utility to create accessible navigation/action anchors with icons.
   *
   * @param {string} id - The ID attribute for the anchor.
   * @param {string} title - The title/tooltip attribute.
   * @param {string} text - The label text or Material Icon ligature name.
   * @returns {HTMLAnchorElement} The created anchor element.
   */
  function createLink(id, title, text) {
    var link = createElement('a', '', text);
    link.id = id;
    link.href = '#';
    link.title = title;
    if (id === 'arrow-back' || id === 'menu') {
      var icon = createElement('i', 'material-icons', text);
      link.textContent = '';
      link.appendChild(icon);
    }
    return link;
  }

  /**
   * Prepares an individual `.codelab-step` section:
   * 1. Wraps raw content inside an `.instructions` card container.
   * 2. Prepends an `h2.step-title` with the step's label.
   * 3. Runs syntax highlighting (`window.prettyPrintOne`) on all `pre code` blocks.
   * 4. Attaches a click handler to code blocks to dispatch copy telemetry events.
   *
   * @param {HTMLElement} step - The `.codelab-step` section element.
   */
  function prepareStep(step) {
    var label = step.getAttribute('data-label') || '';
    var content = createElement('div', 'instructions');
    var heading = createElement('h2', 'step-title', label);
    var fragment = document.createDocumentFragment();

    while (step.firstChild) {
      fragment.appendChild(step.firstChild);
    }
    content.appendChild(heading);
    content.appendChild(fragment);
    step.appendChild(content);

    step.querySelectorAll('pre code').forEach(function (code) {
      if (typeof window.prettyPrintOne === 'function') {
        code.innerHTML = window.prettyPrintOne(code.innerHTML);
      }
    });
  }

  /**
   * Initializes the codelab interactive application inside the specified root element.
   * Builds the title bar, side drawer, main container, controls, and sets up state listeners.
   *
   * @param {HTMLElement} root - The container element with class `.codelab`.
   */
  function init(root) {
    var steps = Array.prototype.slice.call(root.children).filter(function (child) {
      return child.classList.contains('codelab-step');
    });
    var title = root.getAttribute('data-title') || 'Codelab';
    var id = root.getAttribute('id') || 'codelab';
    var current = -1;
    var titleBar = createElement('div');
    var navButtons = createElement('div');
    var back = createLink('arrow-back', 'Back', 'close');
    var menu = createLink('menu', 'Open menu', 'menu');
    var titleHeading = createElement('h1', '', title);
    var main = createElement('div');
    var drawer = createElement('div');
    var drawerSteps = createElement('div', 'steps');
    var drawerList = createElement('ol');
    var stepsContainer = createElement('div');
    var controls = createElement('div');
    var fabs = createElement('div');
    var previous = createLink('previous-step', 'Previous step', 'Back');
    var next = createLink('next-step', 'Next step', 'Next');
    var done = createLink('done', 'Codelab complete', 'Done');
    var time = createElement('div');
    var storageKey = 'progress_' + id;

    // Build header navigation and title bar
    titleBar.id = 'codelab-title';
    navButtons.id = 'codelab-nav-buttons';
    navButtons.appendChild(back);
    navButtons.appendChild(menu);
    titleBar.appendChild(navButtons);
    // Create title heading and author
    var titleHeading = createElement('h1', '', title);
    var authorName = root.getAttribute('data-author') || '';
    var authorSpan = createElement('span', 'author', authorName);
    if (!authorName) { authorSpan.style.display = 'none'; }
    var titleContainer = createElement('div', 'title-container');
    titleContainer.appendChild(titleHeading);
    titleContainer.appendChild(authorSpan);
    titleBar.appendChild(titleContainer);

    // Build side drawer and main reading viewport
    main.id = 'main';
    drawer.id = 'drawer';
    drawerSteps.appendChild(drawerList);
    drawer.appendChild(drawerSteps);
    stepsContainer.id = 'steps';
    controls.id = 'controls';
    fabs.id = 'fabs';
    fabs.appendChild(previous);
    fabs.appendChild(createElement('div', 'spacer'));
    fabs.appendChild(next);
    fabs.appendChild(done);
    controls.appendChild(fabs);
    main.appendChild(stepsContainer);
    main.appendChild(controls);

    // Prepare steps and build the drawer navigation list
    steps.forEach(function (step, index) {
      var item = createElement('li');
      var link = createLink('', '', step.getAttribute('data-label') || '');
      prepareStep(step);
      step.classList.add('codelab-step');
      step.hidden = true;
      item.appendChild(link);
      drawerList.appendChild(item);
      stepsContainer.appendChild(step);
      link.addEventListener('click', function (event) {
        event.preventDefault();
        select(index);
      });
    });

    // Replace original contents with newly constructed dynamic layout
    root.textContent = '';
    root.appendChild(titleBar);
    root.appendChild(drawer);
    root.appendChild(main);

    /**
     * Calculates and updates the remaining minutes display based on the current step.
     * Sums `data-duration` attributes from the current step index to the end.
     *
     * @param {number} index - Active step index.
     */
    function updateTime(index) {
      var remaining = 0;
      for (var stepIndex = index; stepIndex < steps.length; stepIndex += 1) {
        remaining += parseInt(steps[stepIndex].getAttribute('data-duration') || '0', 10) || 0;
      }
      time.textContent = remaining + (remaining === 1 ? ' min remaining' : ' mins remaining');
    }

    /**
     * Activates a step by its zero-based index:
     * - Clamps index within bounds [0, steps.length - 1].
     * - Toggles `selected` attribute and `hidden` property on current/previous step elements.
     * - Applies directional entry animation (`step-enter-next` or `step-enter-previous`).
     * - Toggles visibility of Previous, Next, and Done buttons.
     * - Synchronizes URL hash (`#<index>`) and updates `localStorage`.
     * - Dispatches `google-codelab-pageview` event.
     *
     * @param {number} index - Desired step index to navigate to.
     * @param {boolean} [updateUrl=true] - Whether to push/replace URL hash.
     */
    function select(index, updateUrl) {
      if (!steps.length) {
        return;
      }
      index = Math.min(Math.max(0, index), steps.length - 1);
      if (current === index) {
        return;
      }
      var previousIndex = current;
      if (current >= 0) {
        steps[current].removeAttribute('selected');
        steps[current].classList.remove('is-selected');
        steps[current].hidden = true;
        drawerList.children[current].removeAttribute('selected');
      }
      current = index;
      steps[current].setAttribute('selected', '');
      steps[current].classList.add('is-selected');
      steps[current].hidden = false;
      drawerList.children[current].setAttribute('selected', '');
      // Reset scroll position so the new step always starts at the top.
      stepsContainer.scrollTop = 0;
      if (previousIndex >= 0) {
        var animatedStep = steps[current];
        var animationClass = index > previousIndex ? 'step-enter-next' : 'step-enter-previous';
        animatedStep.classList.add(animationClass);
        window.setTimeout(function () {
          animatedStep.classList.remove('step-enter-next', 'step-enter-previous');
        }, 360);
      }
      previous.hidden = current === 0;
      next.hidden = current === steps.length - 1;
      done.hidden = !next.hidden;
      updateTime(current);
      if (updateUrl !== false) {
        history.replaceState({ step: current }, document.title, '#' + current);
      }
      try {
        localStorage.setItem(storageKey, String(current));
      } catch (error) {
        // Ignore storage failures (e.g. private mode).
      }
      // dispatch(root, 'google-codelab-pageview', {
      //   page: location.pathname + '#' + current,
      //   title: steps[current].getAttribute('data-label') || ''
      // });
    }

    // Attach event listeners for controls and drawer toggling
    previous.addEventListener('click', function (event) {
      event.preventDefault();
      select(current - 1);
    });
    next.addEventListener('click', function (event) {
      event.preventDefault();
      select(current + 1);
    });
    done.addEventListener('click', function (event) {
      event.preventDefault();
      // dispatch(root, 'google-codelab-action', {
      //   category: 'codelab',
      //   action: 'complete',
      //   label: title
      // });
    });
    menu.addEventListener('click', function (event) {
      event.preventDefault();
      root.toggleAttribute('drawer--open');
    });
    back.addEventListener('click', function (event) {
      event.preventDefault();
      root.removeAttribute('drawer--open');
    });
    window.addEventListener('popstate', function () {
      var hash = parseInt(location.hash.slice(1), 10);
      if (!isNaN(hash)) {
        select(hash, false);
      }
    });

    // Mount time counter and restore initial step from URL hash or localStorage
    time.id = 'time-remaining';
    titleBar.appendChild(time);
    var hashIndex = parseInt(location.hash.slice(1), 10);
    var savedIndex = null;
    try {
      savedIndex = parseInt(localStorage.getItem(storageKey), 10);
    } catch (error) {
      // Ignore storage failures.
    }
    select(!isNaN(hashIndex) ? hashIndex : !isNaN(savedIndex) ? savedIndex : 0, false);
   // dispatch(root, 'google-codelab-ready');
  }

  /**
   * Scans document for uninitialized `.codelab` elements and starts them.
   */
  function start() {
    document.querySelectorAll('.codelab').forEach(function (root) {
      if (!root.dataset.initialized) {
        root.dataset.initialized = 'true';
        init(root);
      }
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start);
  } else {
    start();
  }
}());
